-- ============================================================================
-- Migration 0093: P4.B G9 — CAD import jobs (STEP AP242 + DXF)
-- Tracks file uploads, parsing status, and the candidate measurement points
-- generated by the parser before user confirmation.
-- ============================================================================

CREATE TABLE IF NOT EXISTS "cad_import_jobs" (
  "id" serial PRIMARY KEY,
  "productModelId" integer NOT NULL,
  "format" varchar(20) NOT NULL,        -- 'step' | 'dxf'
  "fileName" varchar(255) NOT NULL,
  "fileKey" varchar(255),
  "fileUrl" text,
  "fileSizeBytes" bigint,
  "fileSha256" varchar(64),
  "status" varchar(20) NOT NULL DEFAULT 'queued',
                                          -- queued | parsing | parsed | applied | failed | cancelled
  "parserVersion" varchar(40),
  "entityCounts" jsonb,                  -- format-specific (e.g. {circles: 120, lines: 540})
  "candidatePointCount" integer DEFAULT 0,
  "appliedPointCount" integer DEFAULT 0,
  "errorMessage" text,
  "uploadedBy" integer,
  "appliedBy" integer,
  "appliedAt" timestamp,
  "createdAt" timestamp NOT NULL DEFAULT NOW(),
  "updatedAt" timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT "chk_cad_import_jobs_format"
    CHECK ("format" IN ('step','dxf')),
  CONSTRAINT "chk_cad_import_jobs_status"
    CHECK ("status" IN ('queued','parsing','parsed','applied','failed','cancelled'))
);

CREATE INDEX IF NOT EXISTS "idx_cad_import_jobs_product"
  ON "cad_import_jobs" ("productModelId");
CREATE INDEX IF NOT EXISTS "idx_cad_import_jobs_status"
  ON "cad_import_jobs" ("status");
CREATE INDEX IF NOT EXISTS "idx_cad_import_jobs_created"
  ON "cad_import_jobs" ("createdAt");

CREATE TABLE IF NOT EXISTS "cad_import_candidates" (
  "id" serial PRIMARY KEY,
  "jobId" integer NOT NULL,
  "candidateIndex" integer NOT NULL,
  "code" varchar(100),
  "name" varchar(255),
  "shape" varchar(20) NOT NULL DEFAULT 'circle',
  "positionX" numeric(15, 6) NOT NULL,
  "positionY" numeric(15, 6) NOT NULL,
  "positionZ" numeric(15, 6),
  "radius" numeric(15, 6),
  "geometry" jsonb,
  "sourceEntityType" varchar(60),       -- DXF: CIRCLE | LINE | POLYLINE; STEP: ADVANCED_FACE | ...
  "sourceEntityId" varchar(120),
  "selected" boolean NOT NULL DEFAULT true,
  "createdAt" timestamp NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_cad_import_candidates_job"
  ON "cad_import_candidates" ("jobId");
CREATE UNIQUE INDEX IF NOT EXISTS "uq_cad_import_candidates_job_idx"
  ON "cad_import_candidates" ("jobId","candidateIndex");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_cad_import_candidates_job'
  ) THEN
    ALTER TABLE "cad_import_candidates"
      ADD CONSTRAINT "fk_cad_import_candidates_job"
      FOREIGN KEY ("jobId") REFERENCES "cad_import_jobs" ("id") ON DELETE CASCADE;
  END IF;
END $$;
