{{- if .Values.podDisruptionBudget.enabled -}}
{{/* PDB for the SERVER deployment. doc 33 §11 / ADR-007. */}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "synapse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
{{- end }}
