#!/usr/bin/env node
/**
 * doc 44 W2-B3 (G1.13) — Mapping-as-code EXPORT CLI (SYNAPSE Tầng-1 Chương 10).
 *
 * Export mapping của TẤT CẢ device adapter (device_tags + uns_tag_mappings)
 * ra contracts/mappings/{adapter-code}.mapping.yaml — để commit vào Git & review.
 *
 * Cách dùng (theo pattern migrate-standalone.mjs — đọc DATABASE_URL từ .env):
 *   node scripts/mappings-export.mjs                 (export tất cả)
 *   node scripts/mappings-export.mjs --adapter plc-1 (chỉ một adapter)
 *   node scripts/mappings-export.mjs --out <dir>     (đổi thư mục đích)
 *
 * Ổn định diff Git: thứ tự key cố định + tags/uns_mappings sort theo name —
 * cùng dữ liệu ⇒ cùng bytes. Exit 0 khi OK, 1 khi lỗi.
 *
 * LƯU Ý: format phải khớp server/services/ot/mappingAsCode.ts (buildMappingFile).
 * Đổi format ở một nơi thì đổi cả hai.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.join(__dirname, '..');

// ─── args ─────────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
function argValue(flag) {
  const i = args.indexOf(flag);
  return i >= 0 && i + 1 < args.length ? args[i + 1] : null;
}
const ONLY_ADAPTER = argValue('--adapter');
const OUT_DIR = path.resolve(argValue('--out') ?? path.join(ROOT, 'contracts', 'mappings'));

// ─── .env loader (same as migrate-standalone.mjs) ────────────────────────────
function loadEnvFile(envPath) {
  if (!fs.existsSync(envPath)) return;
  const content = fs.readFileSync(envPath, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.substring(0, idx).trim();
    let value = trimmed.substring(idx + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (!process.env[key]) process.env[key] = value;
  }
}
loadEnvFile(path.join(process.cwd(), '.env'));
loadEnvFile(path.join(ROOT, '.env'));

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error('ERROR: DATABASE_URL not set (set in .env or environment).');
  process.exit(1);
}

// ─── deps from node_modules (postgres + yaml — đã có trong package.json) ─────
let postgres, YAML;
try {
  postgres = (await import('postgres')).default;
  YAML = await import('yaml');
} catch (e) {
  console.error('ERROR: cannot import "postgres"/"yaml" (npm install?):', e.message);
  process.exit(1);
}

const needsSsl = DATABASE_URL.includes('sslmode=require') || DATABASE_URL.includes('ssl=true');
const sql = postgres(DATABASE_URL, {
  ...(needsSsl ? { ssl: { rejectUnauthorized: false } } : {}),
  connect_timeout: 30,
  max: 1,
});

// ─── shared shape helpers (mirror mappingAsCode.buildMappingFile) ────────────
const HEADER = '# generated by mappings-export — REVIEW trước khi import (PR bắt buộc, xem contracts/mappings/README.md)\n';

function toNum(v, fallback) {
  if (v === null || v === undefined) return fallback;
  const n = typeof v === 'number' ? v : Number(v);
  return Number.isFinite(n) ? n : fallback;
}

function normalizeTransform(t) {
  if (!t) return null;
  const out = {};
  for (const k of ['rename', 'scale', 'offset', 'unit', 'cast', 'deadband']) {
    if (t[k] !== undefined && t[k] !== null) out[k] = t[k];
  }
  return Object.keys(out).length ? out : null;
}

function buildMappingFile(adapter, machineCode, tags, mappings, version) {
  const fileTags = [...tags]
    .sort((a, b) => (a.tagKey < b.tagKey ? -1 : a.tagKey > b.tagKey ? 1 : 0))
    .map((t) => ({
      name: t.tagKey,
      address: t.address,
      datatype: t.dataType,
      ...(t.unit != null ? { unit: t.unit } : {}),
      scale: toNum(t.scale, 1),
      offset: toNum(t.offset, 0),
      writable: t.writable,
      enabled: t.isEnabled,
      ...(t.deadband != null ? { deadband: t.deadband } : {}),
      ...(t.samplingMs != null ? { sampling_ms: t.samplingMs } : {}),
    }));
  const fileMappings = [...mappings]
    .sort((a, b) => (a.tag < b.tag ? -1 : a.tag > b.tag ? 1 : 0))
    .map((m) => {
      const transform = normalizeTransform(m.transform);
      return {
        tag: m.tag,
        uns_topic: m.unsTopic,
        ...(m.sparkplugMetric != null ? { sparkplug_metric: m.sparkplugMetric } : {}),
        enabled: m.enabled,
        ...(transform ? { transform } : {}),
        ...(m.notes != null && m.notes !== '' ? { notes: m.notes } : {}),
      };
    });
  return {
    version,
    adapter: adapter.code,
    machine: machineCode,
    vendor: adapter.protocol,
    tags: fileTags,
    uns_mappings: fileMappings,
  };
}

function safeFileName(code) {
  return `${code.replace(/[^A-Za-z0-9._-]/g, '_')}.mapping.yaml`;
}

// ─── main ─────────────────────────────────────────────────────────────────────
try {
  const adapters = ONLY_ADAPTER
    ? await sql`SELECT id, code, protocol, "machineId" FROM device_adapters WHERE code = ${ONLY_ADAPTER} ORDER BY code`
    : await sql`SELECT id, code, protocol, "machineId" FROM device_adapters ORDER BY code`;

  if (ONLY_ADAPTER && adapters.length === 0) {
    console.error(`ERROR: adapter "${ONLY_ADAPTER}" không tồn tại.`);
    await sql.end();
    process.exit(1);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });

  let written = 0;
  for (const a of adapters) {
    let machineCode = null;
    if (a.machineId != null) {
      const m = await sql`SELECT code FROM machines WHERE id = ${a.machineId} LIMIT 1`;
      machineCode = m[0]?.code ?? null;
    }
    const tags = await sql`
      SELECT "tagKey", address, "dataType", unit, scale, "offset", writable, "isEnabled", deadband, "samplingMs"
      FROM device_tags WHERE "adapterId" = ${a.id} ORDER BY "tagKey"`;
    const mappings = await sql`
      SELECT tag, "unsTopic", "sparkplugMetric", transform, enabled, notes
      FROM uns_tag_mappings WHERE "adapterId" = ${a.id} ORDER BY tag`;
    // version metadata: config_snapshots (entity_type='mapping_file', entity_id=adapter.id)
    const snap = await sql`
      SELECT payload_summary FROM config_snapshots
      WHERE entity_type = 'mapping_file' AND entity_id = ${a.id} LIMIT 1`;
    const storedVersion = Number(snap[0]?.payload_summary?.version);
    const version = Number.isFinite(storedVersion) && storedVersion >= 1 ? storedVersion : 1;

    const file = buildMappingFile(a, machineCode, tags, mappings, version);
    const yamlText = HEADER + YAML.stringify(file, { lineWidth: 0 });
    const target = path.join(OUT_DIR, safeFileName(a.code));
    fs.writeFileSync(target, yamlText, 'utf-8');
    console.log(`  [OK] ${path.relative(ROOT, target)}  (version ${version}, ${tags.length} tag, ${mappings.length} uns_mapping)`);
    written++;
  }

  console.log(`\nExported ${written} mapping file(s) → ${OUT_DIR}`);
  await sql.end();
  process.exit(0);
} catch (e) {
  console.error('ERROR:', e.message);
  await sql.end();
  process.exit(1);
}
