/**
 * doc 44 Batch W2-B3 (gap G1.13) — Mapping-as-code (SYNAPSE Tầng-1 Chương 10).
 *
 * ════════════════════════════════════════════════════════════════════════════
 * "Ánh xạ là 'hợp đồng khai báo' (as-code) gắn địa chỉ thô của hãng với
 *  tag/đơn vị/scale canonical — nơi tri thức tích hợp được ghi lại tường minh,
 *  versioned" (spec §10.1). Mapping hiện sống trong DB (device_tags +
 *  uns_tag_mappings); module này thêm vòng Git quanh nó:
 *
 *    export  → contracts/mappings/{adapter-code}.mapping.yaml (ổn định thứ tự
 *              key + sort tag theo name ⇒ diff Git sạch) → commit → PR review
 *    import  → parse + zod validate chặt → diff với DB → (dry-run | apply)
 *              upsert theo KHÓA TỰ NHIÊN (adapter code + tag name — không id số
 *              ⇒ portable giữa env) trong MỘT transaction.
 *
 * AN TOÀN / BẤT BIẾN:
 *   • Import KHÔNG tạo adapter (file không mang endpoint/credentials) — adapter
 *     phải tồn tại trước (onboarding §20). KHÔNG đổi machineId/endpoint.
 *   • Import KHÔNG xoá tag/mapping DB vắng mặt trong file trừ khi `prune:true`
 *     tường minh (diff vẫn LIỆT KÊ chúng để reviewer thấy).
 *   • Import KHÔNG restart adapter — trả `requiresAdapterRestart` để người vận
 *     hành quyết (tag đổi chỉ có hiệu lực ở lần (re)connect kế của otManager).
 *   • Đây là cấu hình READ-DIRECTION (polling + publish). Không mở đường ghi
 *     xuống thiết bị; `writable` chỉ KHAI BÁO — write thật vẫn đi qua
 *     commandDispatcher với đủ gate như trước.
 *
 * VERSION METADATA (quyết định — KHÔNG migration mới):
 *   Bảng config_snapshots (0252) sẵn có với unique (entity_type, entity_id).
 *   Ta lưu MỘT row per adapter: entity_type = 'mapping_file' (text column —
 *   giá trị mới ngoài union app-level 'adapter'|'machine_tags'; cast có chủ
 *   đích + KHÔNG đụng drizzle/** — sweep config-drift chỉ query 'adapter' nên
 *   không va chạm), entity_id = deviceAdapters.id, payload_summary.version =
 *   version đã import gần nhất. Import đòi file.version >= version đã lưu
 *   (chặn regression file cũ đè file mới).
 *
 * SAU KHI APPLY (best-effort, không rollback import nếu lỗi):
 *   • audit qua auditTrailService.logCrudOperation (pattern hiện có),
 *   • unsMappingService.clearMappingCache() (mapping cache read-through),
 *   • configDriftService.approveCurrentConfig(adapterId) — file đã qua PR
 *     review ⇒ import = bản approved mới (baseline drift refresh).
 * ════════════════════════════════════════════════════════════════════════════
 */
import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { z } from "zod";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import { and, asc, eq } from "drizzle-orm";
import { deviceAdapters, deviceTags, unsTagMappings, configSnapshots, machines } from "../../../drizzle/schema";
import type { ConfigSnapshotEntityType } from "../../../drizzle/schema/assetRegistry";
import type { UnsTagTransform } from "../../../drizzle/schema/ot";

// ─── Constants ────────────────────────────────────────────────────────────────

/** Thư mục chứa YAML export — versioned trong Git (mirrors CANONICAL_CONTRACTS_DIR). */
export const MAPPINGS_DIR = path.resolve(process.cwd(), "contracts", "mappings");

export const MAPPING_FILE_SUFFIX = ".mapping.yaml";

/**
 * entity_type cho row metadata version trong config_snapshots. Cast có chủ đích:
 * cột là text (app-validated union, KHÔNG pg enum) — thêm giá trị mới không cần
 * migration; ta không widen union trong drizzle/** (ngoài phạm vi batch này).
 */
const MAPPING_FILE_ENTITY = "mapping_file" as unknown as ConfigSnapshotEntityType;

const MAPPING_FILE_HEADER =
  "# generated by mappings-export — REVIEW trước khi import (PR bắt buộc, xem contracts/mappings/README.md)\n";

// ─── Errors ───────────────────────────────────────────────────────────────────

/** File YAML không qua được zod/parse — `issues` liệt kê từng lỗi. */
export class MappingValidationError extends Error {
  readonly issues: string[];
  constructor(issues: string[]) {
    super(`Mapping file không hợp lệ: ${issues.join("; ")}`);
    this.name = "MappingValidationError";
    this.issues = issues;
  }
}

export type MappingImportErrorCode = "ADAPTER_NOT_FOUND" | "VERSION_REGRESSION" | "DB_UNAVAILABLE";

/** Lỗi nghiệp vụ khi import (adapter không tồn tại / version thụt lùi / mất DB). */
export class MappingImportError extends Error {
  readonly code: MappingImportErrorCode;
  constructor(code: MappingImportErrorCode, message: string) {
    super(message);
    this.name = "MappingImportError";
    this.code = code;
  }
}

// ─── File schema (zod — chặt, .strict() từ chối field lạ) ─────────────────────

const DATATYPES = ["bool", "int", "float", "string", "json"] as const; // khớp otdatatypeenum

const transformSchema = z
  .object({
    rename: z.string().min(1).max(255).optional(),
    scale: z.number().finite().optional(),
    offset: z.number().finite().optional(),
    unit: z.string().max(50).optional(),
    cast: z.enum(["number", "bool", "string"]).optional(),
    deadband: z.number().min(0).optional(),
  })
  .strict();

const fileTagSchema = z
  .object({
    name: z.string().min(1).max(128),
    address: z.string().min(1).max(255),
    datatype: z.enum(DATATYPES),
    unit: z.string().max(50).nullable().optional(),
    scale: z.number().finite().nullable().optional(),
    offset: z.number().finite().nullable().optional(),
    writable: z.boolean().default(false),
    enabled: z.boolean().default(true),
    deadband: z.number().positive().nullable().optional(),
    sampling_ms: z.number().int().min(1).max(86_400_000).nullable().optional(),
  })
  .strict();

const fileUnsMappingSchema = z
  .object({
    tag: z.string().min(1).max(128),
    uns_topic: z.string().min(1).max(500),
    sparkplug_metric: z.string().max(255).nullable().optional(),
    enabled: z.boolean().default(true),
    transform: transformSchema.nullable().optional(),
    notes: z.string().max(4000).nullable().optional(),
  })
  .strict();

export const mappingFileSchema = z
  .object({
    version: z.number().int().min(1),
    adapter: z.string().min(1).max(64),
    machine: z.string().max(50).nullable().optional(),
    vendor: z.string().max(64).nullable().optional(),
    tags: z.array(fileTagSchema).default([]),
    uns_mappings: z.array(fileUnsMappingSchema).default([]),
  })
  .strict()
  .superRefine((file, ctx) => {
    const tagNames = new Set<string>();
    for (const t of file.tags) {
      if (tagNames.has(t.name)) {
        ctx.addIssue({ code: z.ZodIssueCode.custom, message: `tag trùng lặp: "${t.name}"`, path: ["tags"] });
      }
      tagNames.add(t.name);
    }
    const mapTags = new Set<string>();
    for (const m of file.uns_mappings) {
      if (mapTags.has(m.tag)) {
        ctx.addIssue({ code: z.ZodIssueCode.custom, message: `uns_mapping trùng lặp cho tag "${m.tag}"`, path: ["uns_mappings"] });
      }
      mapTags.add(m.tag);
    }
  });

export type MappingFile = z.infer<typeof mappingFileSchema>;
export type MappingFileTag = z.infer<typeof fileTagSchema>;
export type MappingFileUns = z.infer<typeof fileUnsMappingSchema>;

// ─── Row inputs (tách khỏi drizzle types để builder/diff thuần khiết) ─────────

export interface AdapterRowInput {
  id: number;
  code: string;
  protocol: string;
  machineId: number | null;
}

export interface TagRowInput {
  tagKey: string;
  address: string;
  dataType: string;
  unit: string | null;
  scale: string | number | null;
  offset: string | number | null;
  writable: boolean;
  isEnabled: boolean;
  deadband: number | null;
  samplingMs: number | null;
}

export interface UnsRowInput {
  tag: string;
  unsTopic: string;
  sparkplugMetric: string | null;
  transform: UnsTagTransform | null;
  enabled: boolean;
  notes: string | null;
}

// ─── Pure helpers ─────────────────────────────────────────────────────────────

/** Deterministic JSON (keys sorted) — local copy để test không phải mock module khác. */
export function stableStringify(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(",")}]`;
  if (value !== null && typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => v !== undefined)
      .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
      .map(([k, v]) => `${JSON.stringify(k)}:${stableStringify(v)}`);
    return `{${entries.join(",")}}`;
  }
  return JSON.stringify(value) ?? "null";
}

/** sha256 hex của dạng canonical (key-sorted) của file — lưu vào config_snapshots. */
export function mappingFileHash(file: MappingFile): string {
  return createHash("sha256").update(stableStringify(file), "utf8").digest("hex");
}

function toNum(v: string | number | null | undefined, fallback: number): number {
  if (v === null || v === undefined) return fallback;
  const n = typeof v === "number" ? v : Number(v);
  return Number.isFinite(n) ? n : fallback;
}

/** Bỏ key undefined + trả null nếu transform rỗng (chuẩn hoá để diff/so sánh). */
function normalizeTransform(t: UnsTagTransform | null | undefined): UnsTagTransform | null {
  if (!t) return null;
  const out: UnsTagTransform = {};
  if (t.rename !== undefined && t.rename !== null) out.rename = t.rename;
  if (t.scale !== undefined && t.scale !== null) out.scale = t.scale;
  if (t.offset !== undefined && t.offset !== null) out.offset = t.offset;
  if (t.unit !== undefined && t.unit !== null) out.unit = t.unit;
  if (t.cast !== undefined && t.cast !== null) out.cast = t.cast;
  if (t.deadband !== undefined && t.deadband !== null) out.deadband = t.deadband;
  return Object.keys(out).length ? out : null;
}

/**
 * Dựng object MappingFile từ rows DB — THỨ TỰ KEY CỐ ĐỊNH + tags/uns_mappings
 * sort theo name/tag ⇒ export lặp lại cho cùng dữ liệu là byte-identical (Git diff sạch).
 * Field optional null bị OMIT (file gọn, diff không nhiễu "unit: null").
 */
export function buildMappingFile(
  adapter: AdapterRowInput,
  machineCode: string | null,
  tags: TagRowInput[],
  mappings: UnsRowInput[],
  version: number,
): MappingFile {
  const fileTags: MappingFileTag[] = [...tags]
    .sort((a, b) => (a.tagKey < b.tagKey ? -1 : a.tagKey > b.tagKey ? 1 : 0))
    .map((t) => ({
      name: t.tagKey,
      address: t.address,
      datatype: t.dataType as MappingFileTag["datatype"],
      ...(t.unit != null ? { unit: t.unit } : {}),
      scale: toNum(t.scale, 1),
      offset: toNum(t.offset, 0),
      writable: t.writable,
      enabled: t.isEnabled,
      ...(t.deadband != null ? { deadband: t.deadband } : {}),
      ...(t.samplingMs != null ? { sampling_ms: t.samplingMs } : {}),
    }));

  const fileMappings: MappingFileUns[] = [...mappings]
    .sort((a, b) => (a.tag < b.tag ? -1 : a.tag > b.tag ? 1 : 0))
    .map((m) => {
      const transform = normalizeTransform(m.transform);
      return {
        tag: m.tag,
        uns_topic: m.unsTopic,
        ...(m.sparkplugMetric != null ? { sparkplug_metric: m.sparkplugMetric } : {}),
        enabled: m.enabled,
        ...(transform ? { transform } : {}),
        ...(m.notes != null && m.notes !== "" ? { notes: m.notes } : {}),
      };
    });

  return {
    version,
    adapter: adapter.code,
    machine: machineCode,
    vendor: adapter.protocol,
    tags: fileTags,
    uns_mappings: fileMappings,
  };
}

/** MappingFile → YAML string (header comment + key order = insertion order). */
export function mappingFileToYaml(file: MappingFile): string {
  return MAPPING_FILE_HEADER + stringifyYaml(file, { lineWidth: 0 });
}

/** Parse + validate chặt một YAML string → MappingFile (throw MappingValidationError). */
export function parseMappingYaml(text: string): MappingFile {
  let raw: unknown;
  try {
    raw = parseYaml(text);
  } catch (err) {
    throw new MappingValidationError([`YAML parse lỗi: ${(err as Error)?.message ?? String(err)}`]);
  }
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) {
    throw new MappingValidationError(["file phải là một YAML object (version/adapter/tags/uns_mappings)"]);
  }
  const parsed = mappingFileSchema.safeParse(raw);
  if (!parsed.success) {
    throw new MappingValidationError(
      parsed.error.issues.map((i) => `${i.path.join(".") || "(root)"}: ${i.message}`),
    );
  }
  return parsed.data;
}

// ─── Diff (pure) ──────────────────────────────────────────────────────────────

export interface FieldChange {
  field: string;
  from: unknown;
  to: unknown;
}

export interface MappingDiff {
  tags: { creates: string[]; updates: Array<{ name: string; changes: FieldChange[] }>; deletes: string[] };
  unsMappings: { creates: string[]; updates: Array<{ tag: string; changes: FieldChange[] }>; deletes: string[] };
  warnings: string[];
  /** Tổng thay đổi phát hiện (kể cả deletes — deletes chỉ THỰC THI khi prune). */
  changeCount: number;
}

interface NormalizedTag {
  address: string;
  datatype: string;
  unit: string | null;
  scale: number;
  offset: number;
  writable: boolean;
  enabled: boolean;
  deadband: number | null;
  samplingMs: number | null;
}

function normalizeFileTag(t: MappingFileTag): NormalizedTag {
  return {
    address: t.address,
    datatype: t.datatype,
    unit: t.unit ?? null,
    scale: t.scale ?? 1,
    offset: t.offset ?? 0,
    writable: t.writable,
    enabled: t.enabled,
    deadband: t.deadband ?? null,
    samplingMs: t.sampling_ms ?? null,
  };
}

function normalizeDbTag(t: TagRowInput): NormalizedTag {
  return {
    address: t.address,
    datatype: t.dataType,
    unit: t.unit ?? null,
    scale: toNum(t.scale, 1),
    offset: toNum(t.offset, 0),
    writable: t.writable,
    enabled: t.isEnabled,
    deadband: t.deadband ?? null,
    samplingMs: t.samplingMs ?? null,
  };
}

interface NormalizedUns {
  unsTopic: string;
  sparkplugMetric: string | null;
  enabled: boolean;
  transform: UnsTagTransform | null;
  notes: string | null;
}

function normalizeFileUns(m: MappingFileUns): NormalizedUns {
  return {
    unsTopic: m.uns_topic,
    sparkplugMetric: m.sparkplug_metric ?? null,
    enabled: m.enabled,
    transform: normalizeTransform(m.transform ?? null),
    notes: m.notes != null && m.notes !== "" ? m.notes : null,
  };
}

function normalizeDbUns(m: UnsRowInput): NormalizedUns {
  return {
    unsTopic: m.unsTopic,
    sparkplugMetric: m.sparkplugMetric ?? null,
    enabled: m.enabled,
    transform: normalizeTransform(m.transform),
    notes: m.notes != null && m.notes !== "" ? m.notes : null,
  };
}

function fieldChanges<T extends Record<string, unknown>>(from: T, to: T): FieldChange[] {
  const changes: FieldChange[] = [];
  for (const key of Object.keys(to)) {
    const a = from[key];
    const b = to[key];
    if (stableStringify(a) !== stableStringify(b)) changes.push({ field: key, from: a, to: b });
  }
  return changes;
}

export interface CurrentDbState {
  tags: TagRowInput[];
  mappings: UnsRowInput[];
  /** machines.code của adapter (null nếu không gắn máy / không tra được). */
  machineCode?: string | null;
  protocol?: string;
}

/** Diff file (desired) vs DB (current). PURE — không I/O. */
export function diffMapping(file: MappingFile, current: CurrentDbState): MappingDiff {
  const warnings: string[] = [];

  if (current.protocol && file.vendor && file.vendor !== current.protocol) {
    warnings.push(`vendor trong file ("${file.vendor}") khác protocol adapter trong DB ("${current.protocol}") — chỉ cảnh báo, không chặn.`);
  }
  if (current.machineCode !== undefined && (file.machine ?? null) !== (current.machineCode ?? null)) {
    warnings.push(
      `machine trong file ("${file.machine ?? "null"}") khác DB ("${current.machineCode ?? "null"}") — import KHÔNG đổi machineId (chỉnh qua UI/router adapter).`,
    );
  }
  const fileTagNames = new Set(file.tags.map((t) => t.name));
  for (const m of file.uns_mappings) {
    if (!fileTagNames.has(m.tag)) {
      warnings.push(`uns_mapping "${m.tag}" không có tag tương ứng trong file — vẫn import (mapping có thể trỏ tag publish ngoài device_tags).`);
    }
  }

  const dbTags = new Map(current.tags.map((t) => [t.tagKey, t]));
  const tagCreates: string[] = [];
  const tagUpdates: Array<{ name: string; changes: FieldChange[] }> = [];
  for (const t of file.tags) {
    const existing = dbTags.get(t.name);
    if (!existing) {
      tagCreates.push(t.name);
      continue;
    }
    const changes = fieldChanges(
      normalizeDbTag(existing) as unknown as Record<string, unknown>,
      normalizeFileTag(t) as unknown as Record<string, unknown>,
    );
    if (changes.length) tagUpdates.push({ name: t.name, changes });
  }
  const tagDeletes = current.tags.map((t) => t.tagKey).filter((k) => !fileTagNames.has(k)).sort();

  const dbMaps = new Map(current.mappings.map((m) => [m.tag, m]));
  const fileMapTags = new Set(file.uns_mappings.map((m) => m.tag));
  const unsCreates: string[] = [];
  const unsUpdates: Array<{ tag: string; changes: FieldChange[] }> = [];
  for (const m of file.uns_mappings) {
    const existing = dbMaps.get(m.tag);
    if (!existing) {
      unsCreates.push(m.tag);
      continue;
    }
    const changes = fieldChanges(
      normalizeDbUns(existing) as unknown as Record<string, unknown>,
      normalizeFileUns(m) as unknown as Record<string, unknown>,
    );
    if (changes.length) unsUpdates.push({ tag: m.tag, changes });
  }
  const unsDeletes = current.mappings.map((m) => m.tag).filter((t) => !fileMapTags.has(t)).sort();

  const changeCount =
    tagCreates.length + tagUpdates.length + tagDeletes.length + unsCreates.length + unsUpdates.length + unsDeletes.length;

  return {
    tags: { creates: tagCreates.sort(), updates: tagUpdates, deletes: tagDeletes },
    unsMappings: { creates: unsCreates.sort(), updates: unsUpdates, deletes: unsDeletes },
    warnings,
    changeCount,
  };
}

// ─── DB loading ───────────────────────────────────────────────────────────────

async function requireDb() {
  const { getDb } = await import("../../db/connection");
  const d = await getDb();
  if (!d) throw new MappingImportError("DB_UNAVAILABLE", "Database không khả dụng");
  return d;
}

async function loadAdapterByCode(d: Awaited<ReturnType<typeof requireDb>>, code: string): Promise<AdapterRowInput | null> {
  const [row] = await d.select().from(deviceAdapters).where(eq(deviceAdapters.code, code)).limit(1);
  if (!row) return null;
  return { id: row.id, code: row.code, protocol: String(row.protocol), machineId: row.machineId ?? null };
}

async function loadMachineCode(d: Awaited<ReturnType<typeof requireDb>>, machineId: number | null): Promise<string | null> {
  if (machineId == null) return null;
  const [m] = await d.select().from(machines).where(eq(machines.id, machineId)).limit(1);
  return m?.code ?? null;
}

async function loadCurrentState(d: Awaited<ReturnType<typeof requireDb>>, adapterId: number): Promise<{ tags: TagRowInput[]; mappings: UnsRowInput[] }> {
  const tagRows = await d.select().from(deviceTags).where(eq(deviceTags.adapterId, adapterId)).orderBy(asc(deviceTags.tagKey));
  const mapRows = await d.select().from(unsTagMappings).where(eq(unsTagMappings.adapterId, adapterId)).orderBy(asc(unsTagMappings.tag));
  return {
    tags: tagRows.map((t) => ({
      tagKey: t.tagKey,
      address: t.address,
      dataType: String(t.dataType),
      unit: t.unit ?? null,
      scale: t.scale as string | null,
      offset: t.offset as string | null,
      writable: t.writable,
      isEnabled: t.isEnabled,
      deadband: t.deadband ?? null,
      samplingMs: t.samplingMs ?? null,
    })),
    mappings: mapRows.map((m) => ({
      tag: m.tag,
      unsTopic: m.unsTopic,
      sparkplugMetric: m.sparkplugMetric ?? null,
      transform: (m.transform as UnsTagTransform | null) ?? null,
      enabled: m.enabled,
      notes: m.notes ?? null,
    })),
  };
}

/** version đã import gần nhất (payload_summary.version của row 'mapping_file'); null = chưa từng. */
async function loadStoredVersion(d: Awaited<ReturnType<typeof requireDb>>, adapterId: number): Promise<number | null> {
  const [row] = await d
    .select()
    .from(configSnapshots)
    .where(and(eq(configSnapshots.entityType, MAPPING_FILE_ENTITY), eq(configSnapshots.entityId, adapterId)))
    .limit(1);
  const v = (row?.payloadSummary as Record<string, unknown> | null | undefined)?.version;
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

// ─── Export ───────────────────────────────────────────────────────────────────

/** Tên file an toàn từ adapter code (chặn path traversal / ký tự lạ). */
export function mappingFileName(adapterCode: string): string {
  return `${adapterCode.replace(/[^A-Za-z0-9._-]/g, "_")}${MAPPING_FILE_SUFFIX}`;
}

export interface ExportResult {
  adapterId: number;
  adapterCode: string;
  file: MappingFile;
  yaml: string;
  fileName: string;
}

/** Export một adapter (theo code) → MappingFile + YAML string (round-trip stable). */
export async function exportAdapterMapping(adapterCode: string): Promise<ExportResult> {
  const d = await requireDb();
  const adapter = await loadAdapterByCode(d, adapterCode);
  if (!adapter) throw new MappingImportError("ADAPTER_NOT_FOUND", `Adapter "${adapterCode}" không tồn tại`);
  const machineCode = await loadMachineCode(d, adapter.machineId);
  const { tags, mappings } = await loadCurrentState(d, adapter.id);
  const version = (await loadStoredVersion(d, adapter.id)) ?? 1;
  const file = buildMappingFile(adapter, machineCode, tags, mappings, version);
  return { adapterId: adapter.id, adapterCode: adapter.code, file, yaml: mappingFileToYaml(file), fileName: mappingFileName(adapter.code) };
}

/** Export TẤT CẢ adapter → ghi file vào contracts/mappings/ (mkdir nếu thiếu). */
export async function exportAllMappings(dir: string = MAPPINGS_DIR): Promise<{ dir: string; written: string[] }> {
  const d = await requireDb();
  const adapters = await d.select().from(deviceAdapters).orderBy(asc(deviceAdapters.code));
  await fs.mkdir(dir, { recursive: true });
  const written: string[] = [];
  for (const a of adapters) {
    const res = await exportAdapterMapping(a.code);
    const target = path.join(dir, res.fileName);
    await fs.writeFile(target, res.yaml, "utf8");
    written.push(res.fileName);
  }
  return { dir, written };
}

/** Liệt kê file *.mapping.yaml trong contracts/mappings (cho router.list). */
export async function listMappingFiles(dir: string = MAPPINGS_DIR): Promise<
  Array<{ fileName: string; adapterCode: string; sizeBytes: number; modifiedAt: string }>
> {
  let names: string[];
  try {
    names = await fs.readdir(dir);
  } catch {
    return []; // thư mục chưa tồn tại = chưa export lần nào
  }
  const out: Array<{ fileName: string; adapterCode: string; sizeBytes: number; modifiedAt: string }> = [];
  for (const name of names.filter((n) => n.endsWith(MAPPING_FILE_SUFFIX)).sort()) {
    try {
      const st = await fs.stat(path.join(dir, name));
      out.push({
        fileName: name,
        adapterCode: name.slice(0, -MAPPING_FILE_SUFFIX.length),
        sizeBytes: st.size,
        modifiedAt: st.mtime.toISOString(),
      });
    } catch {
      // file biến mất giữa readdir/stat — bỏ qua
    }
  }
  return out;
}

// ─── Import ───────────────────────────────────────────────────────────────────

export interface ImportOptions {
  /** true (mặc định an toàn): chỉ diff, KHÔNG ghi DB. */
  dryRun?: boolean;
  /** Chỉ khi true mới XOÁ tag/mapping DB vắng mặt trong file. */
  prune?: boolean;
  /** users.id người thực hiện (audit + createdBy). */
  actorId?: number | null;
  /** Tên hiển thị (audit + drift approvedByPrincipal). */
  actorName?: string | null;
  /** Nguồn audit (mặc định "system" — CLI/cron; router truyền "trpc"). */
  source?: "web" | "api" | "mqtt" | "system" | "scheduler" | "trpc" | "orchestration";
}

export interface AppliedCounts {
  tagCreates: number;
  tagUpdates: number;
  tagDeletes: number;
  unsCreates: number;
  unsUpdates: number;
  unsDeletes: number;
}

export interface ImportResult {
  dryRun: boolean;
  prune: boolean;
  adapterId: number;
  adapterCode: string;
  fileVersion: number;
  storedVersion: number | null;
  diff: MappingDiff;
  /** null khi dryRun; số dòng đã ghi khi apply. */
  applied: AppliedCounts | null;
  /**
   * true khi có thay đổi device_tags (address/datatype/scale/enabled/deadband…):
   * otManager chỉ đọc tag-set lúc (re)connect ⇒ người vận hành quyết định restart.
   * Thay đổi CHỈ uns_mappings không cần restart (read-through cache đã clear).
   */
  requiresAdapterRestart: boolean;
}

/**
 * Import một YAML mapping file: validate → version gate → diff → (dryRun | apply).
 * Apply = upsert device_tags + uns_tag_mappings theo (adapter code, tag name) +
 * metadata version, TẤT CẢ trong MỘT transaction. Deletes chỉ khi `prune:true`.
 */
export async function importMapping(yamlText: string, opts: ImportOptions = {}): Promise<ImportResult> {
  const dryRun = opts.dryRun !== false; // mặc định dry-run (an toàn)
  const prune = opts.prune === true;

  const file = parseMappingYaml(yamlText);

  const d = await requireDb();
  const adapter = await loadAdapterByCode(d, file.adapter);
  if (!adapter) {
    throw new MappingImportError(
      "ADAPTER_NOT_FOUND",
      `Adapter "${file.adapter}" không tồn tại — import không tạo adapter (file không mang endpoint/credentials). Tạo adapter trước qua deviceAdapter.create.`,
    );
  }
  const machineCode = await loadMachineCode(d, adapter.machineId);
  const current = await loadCurrentState(d, adapter.id);
  const storedVersion = await loadStoredVersion(d, adapter.id);

  if (storedVersion != null && file.version < storedVersion) {
    throw new MappingImportError(
      "VERSION_REGRESSION",
      `version trong file (${file.version}) < version đã import (${storedVersion}) — file cũ không được đè bản mới. Bump version trong Git rồi import lại.`,
    );
  }

  const diff = diffMapping(file, { ...current, machineCode, protocol: adapter.protocol });

  const tagWrites = diff.tags.creates.length + diff.tags.updates.length + (prune ? diff.tags.deletes.length : 0);
  const requiresAdapterRestart = tagWrites > 0;

  if (dryRun) {
    return {
      dryRun: true,
      prune,
      adapterId: adapter.id,
      adapterCode: adapter.code,
      fileVersion: file.version,
      storedVersion,
      diff,
      applied: null,
      requiresAdapterRestart,
    };
  }

  // ── Apply (một transaction) ──────────────────────────────────────────────
  const fileTagsByName = new Map(file.tags.map((t) => [t.name, t]));
  const fileMapsByTag = new Map(file.uns_mappings.map((m) => [m.tag, m]));
  const now = new Date();

  const applied: AppliedCounts = {
    tagCreates: diff.tags.creates.length,
    tagUpdates: diff.tags.updates.length,
    tagDeletes: prune ? diff.tags.deletes.length : 0,
    unsCreates: diff.unsMappings.creates.length,
    unsUpdates: diff.unsMappings.updates.length,
    unsDeletes: prune ? diff.unsMappings.deletes.length : 0,
  };

  await d.transaction(async (tx) => {
    // device_tags: upsert theo (adapterId, tagKey) — chỉ những tag có thay đổi.
    const tagNamesToWrite = [...diff.tags.creates, ...diff.tags.updates.map((u) => u.name)];
    for (const name of tagNamesToWrite) {
      const t = fileTagsByName.get(name);
      if (!t) continue; // không thể xảy ra (diff sinh từ file) — phòng thủ
      const record = {
        address: t.address,
        dataType: t.datatype as (typeof deviceTags.$inferInsert)["dataType"],
        unit: t.unit ?? null,
        scale: String(t.scale ?? 1),
        offset: String(t.offset ?? 0),
        writable: t.writable,
        isEnabled: t.enabled,
        deadband: t.deadband ?? null,
        samplingMs: t.sampling_ms ?? null,
        updatedAt: now,
      };
      await tx
        .insert(deviceTags)
        .values({ adapterId: adapter.id, tagKey: t.name, ...record })
        .onConflictDoUpdate({ target: [deviceTags.adapterId, deviceTags.tagKey], set: record });
    }
    if (prune) {
      for (const name of diff.tags.deletes) {
        await tx.delete(deviceTags).where(and(eq(deviceTags.adapterId, adapter.id), eq(deviceTags.tagKey, name)));
      }
    }

    // uns_tag_mappings: upsert theo (adapterId, tag) — chỉ những mapping có thay đổi.
    const mapTagsToWrite = [...diff.unsMappings.creates, ...diff.unsMappings.updates.map((u) => u.tag)];
    for (const tag of mapTagsToWrite) {
      const m = fileMapsByTag.get(tag);
      if (!m) continue;
      const record = {
        unsTopic: m.uns_topic,
        sparkplugMetric: m.sparkplug_metric ?? null,
        transform: normalizeTransform(m.transform ?? null),
        enabled: m.enabled,
        notes: m.notes ?? null,
        updatedAt: now,
      };
      await tx
        .insert(unsTagMappings)
        .values({ adapterId: adapter.id, tag: m.tag, createdBy: opts.actorId ?? null, ...record })
        .onConflictDoUpdate({ target: [unsTagMappings.adapterId, unsTagMappings.tag], set: record });
    }
    if (prune) {
      for (const tag of diff.unsMappings.deletes) {
        await tx.delete(unsTagMappings).where(and(eq(unsTagMappings.adapterId, adapter.id), eq(unsTagMappings.tag, tag)));
      }
    }

    // Metadata version (config_snapshots 'mapping_file') — cùng transaction.
    const summary: Record<string, unknown> = {
      version: file.version,
      adapterCode: adapter.code,
      importedAt: now.toISOString(),
      importedBy: opts.actorName ?? (opts.actorId != null ? `user#${opts.actorId}` : "cli"),
      tagCount: file.tags.length,
      mappingCount: file.uns_mappings.length,
      prune,
      fileHash: mappingFileHash(file),
    };
    await tx
      .insert(configSnapshots)
      .values({
        entityType: MAPPING_FILE_ENTITY,
        entityId: adapter.id,
        configHash: mappingFileHash(file),
        status: "in_sync",
        payloadSummary: summary,
        updatedAt: now,
      })
      .onConflictDoUpdate({
        target: [configSnapshots.entityType, configSnapshots.entityId],
        set: { configHash: mappingFileHash(file), status: "in_sync", payloadSummary: summary, updatedAt: now },
      });
  });

  // ── Best-effort hậu kỳ (KHÔNG rollback import nếu lỗi) ───────────────────
  // 1) Audit (pattern auditTrailService hiện có).
  try {
    const { logCrudOperation } = await import("../auditTrailService");
    await logCrudOperation(
      { userId: opts.actorId ?? null, userName: opts.actorName ?? null, source: opts.source ?? "system" },
      {
        action: "mapping_as_code.import",
        entityType: "device_adapter_mapping",
        entityId: adapter.id,
        entityName: adapter.code,
        details: {
          operation: "import",
          metadata: { fileVersion: file.version, storedVersion, prune, applied, changeCount: diff.changeCount },
        },
        status: "success",
      },
    );
  } catch (err) {
    console.warn("[MappingAsCode] audit log failed:", (err as Error)?.message ?? err);
  }

  // 2) UNS mapping read-through cache — mapping rows vừa đổi.
  try {
    const { clearMappingCache } = await import("../unsMappingService");
    clearMappingCache();
  } catch (err) {
    console.warn("[MappingAsCode] clearMappingCache failed:", (err as Error)?.message ?? err);
  }

  // 3) Config-drift baseline refresh: file đã qua PR review ⇒ import = bản
  //    approved mới (G1.11). Lưu ý: approve cả adapter config (endpoint…) —
  //    chấp nhận có chủ đích, vì import là hành vi admin có 2FA + audit.
  try {
    const { approveCurrentConfig } = await import("../assetRegistry/configDriftService");
    await approveCurrentConfig(adapter.id, opts.actorId ?? null, opts.actorName ?? "mapping-as-code import");
  } catch (err) {
    console.warn("[MappingAsCode] config-drift approve failed:", (err as Error)?.message ?? err);
  }

  return {
    dryRun: false,
    prune,
    adapterId: adapter.id,
    adapterCode: adapter.code,
    fileVersion: file.version,
    storedVersion,
    diff,
    applied,
    requiresAdapterRestart,
  };
}
